package service

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestFilterUserTextKeepsOnlyCursorUserQuery(t *testing.T) {
	inputText := `<user_info>
OS Version: win32 10.0.26200
</user_info>

<rules>
<user_rule>Always use Chinese</user_rule>
</rules>

<user_query>
使用日志，请求内容的过滤

<system_reminder>
For the turn that contains this reminder, the active mode is agent.
</system_reminder>

是不是没过滤完整 ？
</user_query>`

	filteredText := filterUserText(inputText)

	assert.Equal(t, "使用日志，请求内容的过滤\n\n是不是没过滤完整 ？", filteredText)
}

func TestFilterUserTextKeepsOnlyCursorUserQueryAfterLocalCommand(t *testing.T) {
	inputText := `<user_query>
<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>
<command-name>/compact</command-name>
            <command-message>compact</command-message>
            <command-args></command-args>
<local-command-stdout>Compacted (ctrl+o to see full summary)
Tip: You have access to Opus 1M with 5x more context</local-command-stdout>
继续
</user_query>`

	filteredText := filterUserText(inputText)

	assert.Equal(t, "继续", filteredText)
}

func TestFilterUserTextStripsAdditionalCursorInjectedTags(t *testing.T) {
	inputText := `请检查这个问题
<system-communication>
- hidden system details
</system-communication>
<attached_files>
secret file context
</attached_files>
<selected_code>
private selected code
</selected_code>
<linter_errors>
private lint output
</linter_errors>`

	filteredText := filterUserText(inputText)

	assert.Equal(t, "请检查这个问题", filteredText)
}
