package service

import (
	"testing"

	"github.com/QuantumNous/new-api/relaykit/dto"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestExtractImageUserMessages(t *testing.T) {
	tests := []struct {
		name     string
		prompt   string
		expected []string
	}{
		{
			name:     "records image generation prompt",
			prompt:   "一只坐在月亮上的橘猫",
			expected: []string{"一只坐在月亮上的橘猫"},
		},
		{
			name:     "trims surrounding whitespace",
			prompt:   "  watercolor mountain landscape  ",
			expected: []string{"watercolor mountain landscape"},
		},
		{
			name:   "skips empty prompt",
			prompt: "   ",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			request := &dto.ImageRequest{Prompt: test.prompt}

			messages := extractImageUserMessages(request)

			require.Len(t, messages, len(test.expected))
			assert.Equal(t, test.expected, messages)
		})
	}
}

func TestFilterUserTextKeepsOnlyCursorUserQuery(t *testing.T) {
	inputText := `<user_info>
OS Version: win32 10.0.26200
</user_info>

<rules>
<user_rule>Always use Chinese</user_rule>
</rules>

<user_query>
使用日志，请求内容的过滤

<system_reminder>
For the turn that contains this reminder, the active mode is agent.
</system_reminder>

是不是没过滤完整 ？
</user_query>`

	filteredText := filterUserText(inputText)

	assert.Equal(t, "使用日志，请求内容的过滤\n\n是不是没过滤完整 ？", filteredText)
}

func TestFilterUserTextKeepsOnlyCursorUserQueryAfterLocalCommand(t *testing.T) {
	inputText := `<user_query>
<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>
<command-name>/compact</command-name>
            <command-message>compact</command-message>
            <command-args></command-args>
<local-command-stdout>Compacted (ctrl+o to see full summary)
Tip: You have access to Opus 1M with 5x more context</local-command-stdout>
继续
</user_query>`

	filteredText := filterUserText(inputText)

	assert.Equal(t, "继续", filteredText)
}

func TestFilterUserTextStripsTranscriptFromCursorUserQuery(t *testing.T) {
	inputText := `<user_query>
使用日志那里过滤掉 

<transcript>
User: 
BEST PRACTICE KPI/METRIC DATA COLLECTION (RAW — NO LEVEL L1-L5 MAPPING YET)

Industry: D05 — 배터리 모듈·팩
Search keywords: 배터리모듈 팩 BMS KPI 제조 수율, battery module pack BMS KPIs manufacturing yield EOL
WebSearch battery module pack manufacturing KPIs yield EOL test metrics
</transcript>
</user_query>`

	filteredText := filterUserText(inputText)

	assert.Equal(t, "使用日志那里过滤掉", filteredText)
}

func TestFilterUserTextDropsExtremelyImportantInjectedBlock(t *testing.T) {
	inputText := `EXTREMELY_IMPORTANT
System-only injected content.`

	filteredText := filterUserText(inputText)

	assert.Empty(t, filteredText)
}

func TestFilterUserTextStripsAgentNotificationTag(t *testing.T) {
	inputText := `<user_query>
继续处理日志过滤

<agent_notification>
Another agent completed a background task with verbose details.
</agent_notification>

确认一下
</user_query>`

	filteredText := filterUserText(inputText)

	assert.Equal(t, "继续处理日志过滤\n\n确认一下", filteredText)
}

func TestFilterUserTextStripsAdditionalCursorInjectedTags(t *testing.T) {
	inputText := `请检查这个问题
<system-communication>
- hidden system details
</system-communication>
<attached_files>
secret file context
</attached_files>
<selected_code>
private selected code
</selected_code>
<linter_errors>
private lint output
</linter_errors>`

	filteredText := filterUserText(inputText)

	assert.Equal(t, "请检查这个问题", filteredText)
}
