import {
  AlertTriangle,
  Coins,
  DollarSign,
  Hash,
  Layers,
  Timer,
  UserCheck,
  UserX,
  Users,
  type LucideIcon,
} from 'lucide-react'
import type { ReactNode } from 'react'
import { useTranslation } from 'react-i18next'

import { IconBadge, type IconBadgeTone } from '@/components/ui/icon-badge'
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from '@/components/ui/tooltip'
import { cn } from '@/lib/utils'

import { getActiveUserRateClassName } from '../lib/active-user-rate'
import type { DepartmentStat } from '../types'
import { ActivityFormulaTooltip } from './activity-formula-tooltip'

export function DepartmentStatsCards(props: { stat: DepartmentStat }) {
  const { t } = useTranslation()
  const stat = props.stat

  const formatTokens = (tokens: number | undefined): string => {
    if (!tokens) return '0'
    return `${(tokens / 1_0000_0000).toFixed(2)} 亿`
  }

  const formatTokensDetail = (tokens: number | undefined): string => {
    if (!tokens) return '0'
    return tokens.toLocaleString()
  }

  const buildTokenBreakdownTooltip = (): ReactNode => {
    const breakdownRows: { label: string; desc: string; value: number }[] = [
      {
        label: t('Uncached Input'),
        desc: t('Uncached input tokens actually sent to the model'),
        value: stat.uncached_input_tokens ?? 0,
      },
      {
        label: t('Uncached Output'),
        desc: t('Output tokens generated by the model'),
        value: stat.uncached_output_tokens ?? 0,
      },
      {
        label: t('Cache Read'),
        desc: t('Input tokens served from the prompt cache'),
        value: stat.cache_read_tokens ?? 0,
      },
      {
        label: t('Cache Write'),
        desc: t('Input tokens written to the prompt cache'),
        value: stat.cache_write_tokens ?? 0,
      },
    ]
    return (
      <div className='text-background max-w-[16rem] space-y-1.5'>
        <div className='flex items-baseline justify-between gap-4'>
          <span className='text-xs'>{t('Total Tokens')}</span>
          <span className='font-mono text-xs font-semibold'>
            {formatTokensDetail(stat.total_tokens)}
          </span>
        </div>
        <div className='border-border/40 space-y-1.5 border-t pt-1.5'>
          {breakdownRows.map((row) => (
            <div key={row.label}>
              <div className='flex items-baseline justify-between gap-4'>
                <span className='text-xs font-medium'>{row.label}</span>
                <span className='font-mono text-xs'>
                  {formatTokens(row.value)}
                </span>
              </div>
              <div className='font-sans text-[11px] leading-snug'>
                {row.desc}
              </div>
            </div>
          ))}
        </div>
      </div>
    )
  }

  const formatCNY = (amount: number | undefined): string => {
    if (!amount) return '¥0'
    return `¥${amount.toFixed(2)}`
  }

  const formatRequests = (count: number | undefined): string => {
    if (!count) return '0'
    if (count >= 1_0000) {
      return `${(count / 1_0000).toFixed(2)} 万`
    }
    return count.toLocaleString()
  }

  const activeUserRate = stat.active_user_rate ?? 0
  const tokensPerActiveUser =
    (stat.avg_tokens_per_active_user_mt ?? 0) * 1_000_000
  const activeUserRateClassName = getActiveUserRateClassName(activeUserRate)

  const items: {
    title: string
    titleSuffix?: ReactNode
    value: string
    desc?: string
    icon: LucideIcon
    iconTone: IconBadgeTone
    valueClassName?: string
    tooltip?: ReactNode
  }[] = [
    {
      title: t('Total Tokens'),
      value: formatTokens(stat.total_tokens),
      desc: t('Statistical tokens'),
      icon: Layers,
      iconTone: 'chart-4',
      tooltip: buildTokenBreakdownTooltip(),
    },
    {
      title: t('Total Cost'),
      value: formatCNY(stat.total_amount_cny),
      desc: t('Statistical quota'),
      icon: Coins,
      iconTone: 'success',
    },
    {
      title: t('Avg Price'),
      value: `${
        !stat.avg_price_per_mt ? '¥0' : `¥${stat.avg_price_per_mt.toFixed(2)}`
      }/MT`,
      desc: t('Average price per million tokens'),
      icon: DollarSign,
      iconTone: 'warning',
    },
    {
      title: t('Total Requests'),
      value: formatRequests(stat.total_requests),
      desc: t('Statistical count'),
      icon: Hash,
      iconTone: 'info',
    },
    {
      title: t('Avg Response Time'),
      value: `${(stat.avg_use_time ?? 0).toFixed(1)}s`,
      desc: t('Average response time'),
      icon: Timer,
      iconTone: 'chart-2',
    },
    {
      title: t('Registered Count'),
      value: (stat.registered_users ?? 0).toLocaleString(),
      desc: t('Registered people count'),
      icon: UserCheck,
      iconTone: 'success',
      valueClassName: 'text-success',
    },
    {
      title: t('Unregistered Count'),
      value: (stat.unregistered_users ?? 0).toLocaleString(),
      desc: t('Unregistered people count'),
      icon: UserX,
      iconTone: 'warning',
      valueClassName: 'text-warning',
    },
    {
      title: t('Users / Share'),
      titleSuffix: (
        <ActivityFormulaTooltip formula={stat.active_user_formula} />
      ),
      value: `${(stat.active_users ?? 0).toLocaleString()} / ${activeUserRate.toFixed(1)}%`,
      desc: t('Users and their share during the selected period'),
      icon: Users,
      iconTone: 'primary',
      valueClassName: activeUserRateClassName,
    },
    {
      title: t('Tokens per Active User'),
      value: formatTokens(tokensPerActiveUser),
      desc: t('Based on active users only'),
      icon: Layers,
      iconTone: 'chart-4',
      tooltip: formatTokensDetail(tokensPerActiveUser),
    },
    {
      title: t('Error Rate'),
      value: `${(stat.error_rate ?? 0).toFixed(1)}%`,
      desc: t('Request error rate'),
      icon: AlertTriangle,
      iconTone: 'destructive',
    },
  ]

  return (
    <div className='overflow-hidden rounded-lg border'>
      <div className='divide-border/60 grid min-w-0 grid-cols-2 divide-x sm:grid-cols-3 lg:grid-cols-5'>
        {items.map((item) => {
          const Icon = item.icon
          return (
            <div
              key={item.title}
              className='min-w-0 px-3 py-2.5 sm:px-5 sm:py-4'
            >
              <div className='flex min-w-0 items-center gap-1.5 sm:gap-2'>
                <IconBadge
                  tone={item.iconTone}
                  size='stat'
                  className='size-4 rounded-sm sm:size-7 sm:rounded-md [&>svg]:size-2.5 sm:[&>svg]:size-3.5'
                >
                  <Icon />
                </IconBadge>
                <div className='text-muted-foreground min-w-0 truncate text-[11px] leading-4 font-medium tracking-wide uppercase sm:text-xs sm:tracking-wider'>
                  {item.title}
                </div>
                {item.titleSuffix}
              </div>
              {item.tooltip ? (
                <Tooltip>
                  <TooltipTrigger
                    render={
                      <div
                        className={cn(
                          'mt-1.5 max-w-full truncate font-mono text-lg font-bold tracking-tight tabular-nums sm:mt-2 sm:text-2xl',
                          item.valueClassName || 'text-foreground'
                        )}
                      />
                    }
                  >
                    {item.value}
                  </TooltipTrigger>
                  <TooltipContent>
                    <div className='font-mono text-xs'>{item.tooltip}</div>
                  </TooltipContent>
                </Tooltip>
              ) : (
                <div
                  className={cn(
                    'mt-1.5 max-w-full truncate font-mono text-lg font-bold tracking-tight tabular-nums sm:mt-2 sm:text-2xl',
                    item.valueClassName || 'text-foreground'
                  )}
                >
                  {item.value}
                </div>
              )}
              {item.desc && (
                <div className='text-muted-foreground/60 mt-1 hidden text-xs md:block'>
                  {item.desc}
                </div>
              )}
            </div>
          )
        })}
      </div>
    </div>
  )
}
